### ISSUE TITLE
iframe mit variabler Höhe ermöglichen

### ISSUE THREAD

**Issue by fenglisch** [msteudtn/Mat-O-Wahl#13]
## Hintergrund
Neben der Standalone-Variante eignet es sich in vielen Fällen, den Mat-O-Wahl als iframe in eine andere Website einzubetten. Mit einem ganz normalen iframe-Tag gelingt das optimal. Schwierig ist einzig und allein die Höhe des iframes, da diese sich standardmäßig nicht an die wechselnde Höhe des Inhaltes anpasst. Aktuell möglich ist daher:
A) Sehr große Höhe (6000 px) und no-scroll, um Platz für die lange Auswertung zu machen und trotzdem doppelte Scrollbars zu vermeiden: https://bonn-o-mat.de/start/ (Beim Ausklappen mehrerer Thesen in der Auswertung ist der Inhalt trotzdem zu lang)
B) Höhe gerade so einstellen, dass mobile Ansicht Platz hat (1000 px): https://www.lebendiges-lueneburg.de/mitwirk-o-mat/ (Problem: doppelte Scrollbars in der Auswertung)

## Konkretes Anliegen
Es fehlt die Funktion, dass sich die Höhe des iframes automatisch an die Höhe des Inhaltes anpasst. Dafür scheint es auf jQuery basierende Lösungen zu geben: https://stackoverflow.com/questions/9162933/make-iframe-height-dynamic-based-on-content-inside-jquery-javascript
Zur Umsetzung fehlt mir jedoch das Know How.

**Comment by msteudtn** [comment]
Ich habe die stackoverflow-Lösung jetzt als Addon hinzugefügt. Sie liegt im Unterordner /EXTRAS/ in der 0.6-er Version, z.B.
https://github.com/msteudtn/Mat-O-Wahl/blob/version-0.6-BMBF-PTF/extras/addon_check_iframe_resize.js

### Wie zu benutzen?
Man kann sie über die DEFINITION.JS einbinden (Abschnitt 2.3) oder manuell mit dem üblichen <script>-Tag.

### Was passiert dort?
Das Skript prüft regelmäßig die Höhe des eigenen <iframe>. Wenn sie sich ändert, wird die Höhe angepasst. Außerdem werden noch 50px extra drauf gerechnet.

### Einschränkungen
Der Mat-o-Wahl nutzt die Bootstrap `CONTAINER-FLUID`-class. Es könnte zu unschönen Rändern (links/rechts) auf kleinen Bildschirmen (Smartphone) kommen. Das habe ich noch nicht weiter geprüft.

### Noch was zu beachten?
Bitte prüfen, ob nicht schon eine CSS "height" existiert.
Außerdem könnte ein `style="width:100%"` im <iframe> recht hilfreich sein. ;) 

### Beispielcode fürs iframe-Laden
```
<body>
	<div>OBEN</div>
	<div>
		MITTE
		<iframe src="../matowahl/index.html" style="width:100%" loading="lazy"></iframe>
	</div>  
	<div>UNTEN</div>
</body>
```
### Beispielcode für DEFINITION.JS

`var addons = ["extras/addon_check_iframe_resize.js"]`

### Beispielcode für Addon-Datei

`keine Einstellungen nötig`

**Comment by fenglisch** [comment]
Du warst ja fix, vielen Dank!

Ich habe es getestet und leider funktioniert es noch nicht auf Anhieb. Die Instanz liegt unter https://mitwirk-o-mat.de/staging und eingebunden ist sie in https://www.lebendiges-lueneburg.de/spielwiese/ mit folgendem Tag:
`<iframe src="https://mitwirk-o-mat.de/iframe/index.html" style="width:100%" loading="lazy"></iframe>`

Die Höhe ist konstant bei 150 px. Die Konsole zeigt aber auch den Error:
```
Uncaught TypeError: this.frameElement is null
    onload https://mitwirk-o-mat.de/iframe/extras/addon_check_iframe_resize.js:29
    EventHandlerNonNull* https://mitwirk-o-mat.de/iframe/extras/addon_check_iframe_resize.js:26
```

Hast du es schon zum Laufen bekommen?

**Comment by msteudtn** [comment]
mmh, ich glaube, hier liegt ein **Cross-Domain**-Aufruf-Problem vor.

Hier kenne ich keine client-seitige Lösung. Stattdessen muss der Server den Aufruf erlauben. Entweder direkt in den Server-Einstellungen oder als einfache `.htaccess`-Datei (Apache).

https://developer.mozilla.org/de/docs/Web/HTTP/Headers/X-Frame-Options

z.B.  `Header set X-Frame-Options "allow-from https://mitwirk-o-mat.de/"  `

Das fehlt noch bei den **Einschränkungen**. :(

**Comment by msteudtn** [comment]
### (Teilweise) Korrektur zum letzten Kommentar

In deinem Quelltext ist die Quelle (`src`) ein Binärcode. Das kommt vermutlich von Wordpress. Der Link ist im `data-src` hinterlegt und wird vom JavaScript-Addon nicht ausgelesen.

Dein (veränderter) Quelltext:
`<iframe  style="width:100%" loading="lazy" data-src="https://mitwirk-o-mat.de/iframe/index.html" class="lazyload" src="data:image/gif;base64,R0...Ow=="></iframe>`

Funktionierender Code:
`<iframe  style="width:100%" loading="lazy" src="https://mitwirk-o-mat.de/iframe/index.html" class="lazyload"></iframe>`

Wenn es dir möglich ist, das zu ändern, sollte es funktionieren.

**Comment by fenglisch** [comment]
Nice, es funktioniert tatsächlich und ist total geschmeidig!
https://www.lebendiges-lueneburg.de/spielwiese/

Ausschlaggebend ist same origin. Ich hab es hier getestet, wo `src` nicht automatisch zu `data-src` wird, aber auch hier klappt nur die Instanz von derselben Domain: https://mitwirk-o-mat.de/formular/index.php/218325

Überrascht hat mich, dass es auch nicht klappt, wenn die Seite mit der Subdomain `www` aufgerufen wird, aber diese in der `src` nicht vorkommt, oder andersherum. Um hier Fehler zu vermeiden, müsste man eine automatische Weiterleitung einrichten, falls diese noch nicht vorhanden ist (von https://www.xxx auf https://xxx oder andersherum). 

Dafür klappt es auf lebendiges-lueneburg.de/spielwiese, obwohl `src` zu `data-src` wird.

Wenn sich Cross-Origin nicht ermöglichen lassen sollte, heißt das für uns wohl, dass wir die Mitwirk-O-Maten jeweils auf derselben Domain hosten müssen, wo sie eingebettet werden sollen, oder in der Server config muss die Domain mitwirk-o-mat.de freigeschaltet werden. Beides erscheint mir etwas umständlich...

**Comment by fenglisch** [comment]
Und die automatische Anpassung klappt zum Teil erst ab der ersten These, davor sind es sogar zwei zusätzliche Scrollbars:

![grafik](https://user-images.githubusercontent.com/61431524/119524081-99925d80-bd7d-11eb-8f5f-8484a24e9bb1.png)

**Comment by msteudtn** [comment]
> Ausschlaggebend ist same origin. Ich hab es hier getestet, wo `src` nicht automatisch zu `data-src` wird, aber auch hier klappt nur die Instanz von derselben Domain: 
> 
> Überrascht hat mich, dass es auch nicht klappt, wenn die Seite mit der Subdomain `www` aufgerufen wird, ...

... ich korrigiere mich erst einmal, was die **X-Frame-Options Header** angeht.

Dieser wird in modernen und mobilen Browsern nicht mehr unterstützt. Stattdessen sollte man auf die (flexiblere?) **Content-Security-Policy: frame-ancestors** zurückgreifen.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-ancestors

Damit muss diese Lösung noch mal angepasst werden.

 
> Wenn sich Cross-Origin nicht ermöglichen lassen sollte, heißt das für uns wohl, dass wir die Mitwirk-O-Maten jeweils auf derselben Domain hosten müssen, wo sie eingebettet werden sollen, oder in der Server config muss die Domain mitwirk-o-mat.de freigeschaltet werden. Beides erscheint mir etwas umständlich...

Auch das sollte über eine eigene `.htaccess`-Datei auf eurem Server möglich sein. Sie wird vermutlich so aussehen:

`Header add Content-Security-Policy: frame-ancestors https://stadt-a.de https://www.stadt-b.de;`


> Und die automatische Anpassung klappt zum Teil erst ab der ersten These, davor sind es sogar zwei zusätzliche Scrollbars:

Der DIV mit den Erläuterungen am Anfang nutzt `vh` als Größe. Das ist die dynamische Größe des Viewports. Vermutlich ist er am Anfang noch nicht berechnet. Beim nächsten Update kann ich den Erklär-DIV ein paar Pixel verändern. Dann sollte sich auch die iframe-Höhe nachziehen.

**Comment by msteudtn** [comment]
### Update

Ich selbst bin mit der **Content-Security-Policy** nicht weiter gekommen. 

Aktueller Stand der Technik für Cross-Domain-Zugriffe ist die `postMessage()`-Funktion. 
https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage
Damit muss auf der iframe-Quelle und der iframe-Einbinde-Seite etwas JavaScript-Code eingefügt werden. 

Das System wäre damit so (ähnlich) wie der bestehende https://github.com/davidjbradshaw/iframe-resizer

### Beispiel für den iframe-resizer von David Bradshaw

#### iframe-Quelle

```
[...] meine einzubindende Seite
<script type="text/javascript" src="https://mat-o-wahl.de/iframe/temp/iframeResizer.contentWindow.min.js"></script>
[...]
```

#### Seite mit dem iframe
```
[...]
 <iframe id="myIframe" src="https://mat-o-wahl.de/iframe/index.html" style="min-width:100%;" loading="lazy"></iframe>
[...]
 <script type="text/javascript" src="https://mat-o-wahl.de/iframe/temp/iframeResizer.min.js"></script> 
 <script>
  iFrameResize({ log: true }, '#myIframe')
 </script>
[...]
```

### Fragen

* Habt ihr Zugriff (oder Einfluss) auf die Seiten, wo ihr eingebunden werdet (z.B. www.stadt-xyz.de) um dort auch Code zu hinterlegen?
* Falls ja, kann man den `postMessage()`-Ansatz weiter verfolgen und/oder das System von David Bradshaw.
* Falls nein, bleibt nur der Zugriff von der gleichen Domain. :(

**Comment by fenglisch** [comment]
Ich dachte schon, es liegt an mir (was tatsächlich in der Regel der Fall ist). Mit `.htaccess` habe ich es zwar geschafft, eine CSP-Regel zum Header hinzufügen (s. https://cspvalidator.org/#url=https://mitwirk-o-mat.de/iframe), aber das hatte leider keine Auswirkung.

Danke, dass du dich nochmal reingewuselt hast!

Zu deinen Fragen: Ja, in der Regel sollte es möglich sein, Javascript-Code zu der Seite hinzuzufügen, in der der Mitwirk-O-Mat eingebettet wird. Wenn das notwendig ist, werden wir das wohl zur Voraussetzung machen (müssen), wenn eine Einbettung gewünscht ist und doppelte Scrollbars unerwünscht sind. Sonst gibt es ja eine Standalone-Instanz ja auch noch als Fallback.

Insofern: Den `postMessage()`-Ansatz bzw. den von Bradshaw weiterzuverfolgen, klingt vielversprechend!

**Comment by msteudtn** [comment]
## Update

neuer Versuch per `postMessage()`-Funktion

Die Partner-Seite, welche den Mat-o-Wahl / Mitwirk-o-Mat per <iframe> einbindet sollte folgendes in ihren Quelltext schreiben.
```
 <script src="https://mitwirk-o-wahl.de/ordner/addon_check_iframe_resize_cross_domain.js"></script>
	
 <iframe id="myIframe" src="https://mitwirk-o-wahl.de/" style="min-width:100%;" loading="lazy"></iframe>
 
<script>
	window.onload = function() {
		fnMatoWahlCrossDomainEventListener("myIframe");
		}
 </script>
```

Im Mitwirk-o-Mat selbst muss dann "nur" das Plugin `addon_check_iframe_resize_cross_domain.js` in der `DEFINITION.JS` aktiviert werden, z.B. so:
`var addons = ["extras/addon_check_iframe_resize_cross_domain.js"]`

### Einschränkungen

* Es könnte sein, dass die Partnerseite (mit dem <iframe>) das Laden der Javascript-Datei vom fremden Server verweigert. In dem Fall sollte es reichen, wenn sie auch beim Partner gehostet wird.
* Wenn der <iframe> seine Größe ändert, springt er nicht mehr zurück. (Anders als beim `same_domain`-Skript.) Irgendwann werde ich beide Skripte in eins zusammenführen.
* Ich habe ein Intervall von 1,5 Sekunden (1500 ms) eingebaut. Nach dieser Zeit wird die innere Höhe des <iframe> wieder geprüft.
* Am Anfang baut sich der <iframe> etwas "komisch" auf. Das liegt wieder an dem 1,5 Sekunden-Intervall und der Beschreibungs-Box mit einer variablen Höhe. :( 

### Download

Das Plugin befindet sich im Ordner EXTRAS. Im Moment ist es noch in der aktuellen Version 0.6 und noch nicht im Master. https://github.com/msteudtn/Mat-O-Wahl/tree/version-0.6-BMBF-PTF

**Comment by fenglisch** [comment]
Ja, es funktioniert!
S. zweiter iframe auf dieser Seite: https://www.lebendiges-lueneburg.de/spielwiese/

Wenn du schreibst, dass du die beiden Skripte irgendwann zusammenführen wirst, wird dann bei Cross Origin (wie auch bei Same Origin) eine Anpassung der Höhe nach unten möglich sein, also dass der iframe wieder kleiner wird?

Durch das 1500er-Intervall wird das ganze ziemlich ruckelig. Testweise habe ich es auf 150 und 15 umgestellt, womit es schon deutlich geschmeidiger ist. Zu Demonstrationszwecken habe ich es aber wieder zurück auf 1500 gestellt. Spricht etwas dagegen, das Intervall zu verkleinern?

Die Komplikationen beim Laden der Begrüßungsbox sind mir auch aufgefallen. Z. T. lassen die sich ja durch ein kürzeres Intervall vermeiden. Bei der Höhe der Box frage ich mich, ob `height: 60vh` nötig ist. Ganz ohne Height-Attribut ist die Box ziemlich eng. Ich habe deswegen das Height-Attribut durch `padding: 5% 0` ersetzt. Das Padding und damit die Größe der Box hängen dann ja ebenfalls von der Breite der Box, also der Breite des Bildschirms ab. Sieht für mich auf den ersten Blick ganz gut aus (stand alone, iframe, Desktop und mobil hochkant und quer): https://mitwirk-o-mat.de/iframe/

**Comment by msteudtn** [comment]
Das **Intervall** kann problemlos verringert werden. Ich dachte erst, dass der CPU-Lüfter aufdreht aber auch ein kleineres Intervall stellt kein Problem dar. Ich würde (aus dem Bauch heraus) auf `250ms` gehen.

Die anderen beiden Punkte habe ich in extra Tickets ausgelagert, so dass **das Thema hier geschlossen** werden kann. Prinzipiell ist die Aufgabe ja erledigt.
