### ISSUE TITLE
In "resultsShortTable" ein Plus/Minus-Button zum aus-/einklappen der "resultsShortPartyDescription" einfügen (nur Desktop)

### ISSUE THREAD

**Issue by fenglisch** [msteudtn/Mat-O-Wahl#15]
In der Desktop-Ansicht könnte ein Plus/Minus-Button (analog zu dem in "resultsByThesisTable" und "resultsByPartyTable") den Nutzer*innen bei helfen zu erkennen, dass sie auf die Zeile klicken können, um die Kurzbeschreibung auszuklappen. Weiterhin sollte die Beschreibung jedoch beim Klick auf die ganze Zeile aus- und zuklappen, nicht nur beim Button.

Da die Zeilen in der mobilen Ansicht schon ziemlich voll sind, eignet sich der Button vermutlich nur in der Desktop-Ansicht.

**Comment by msteudtn** [comment]
Inzwischen wird in der Anfangsansicht (bei den Ergebnissen) ein Teil der Partei-Beschreibung angezeigt. Der Rest ist mit drei Punkten abgeschnitten. ("...")

Das **sollte** genügen um die Nutzer und Nutzerinnen darauf aufmerksam zu machen, dass da noch etwas versteckt ist.

Ich empfehle deshalb, das Ticket zu schließen.

**Comment by fenglisch** [comment]
Ja, das stimmt. Ich hatte da ja auch ein ::before-Pseudo-Element mit Content "Beschreibung anzeigen" eingefügt und das jetzt zu einem Quasi-Button umgewandelt (anstelle des Bullet Points und der drei Punkte)
![grafik](https://user-images.githubusercontent.com/61431524/217483124-18098f34-9a94-45c0-821e-73f59166c91e.png)
Bzw.
![grafik](https://user-images.githubusercontent.com/61431524/217483221-b9eed907-f1fd-4886-95a4-5cb77b6172f8.png)

Lange Rede, kurzer Sinn, die aktuelle Variante bietet bereits genug Flexibilität 👍
