### ISSUE TITLE
Fehler in statistischer Auswertung beheben

### ISSUE THREAD

**Issue by fenglisch** [msteudtn/Mat-O-Wahl#17]
Dies ist ein Sammelticket, das Fehler in der statistischen Auswertung aufzählt und denn Soll-Zustand beschreibt. Die Fehler liegen teilweise in der Darstellung (results.html/js), teilweise in der Erfassung.

IST: "Doppelt gewichtigen" + "Überspringen" -> 198
SOLL: 99

IST: jumpToQuestion erzeugt keinen Wert, wird in "resultsQuestions" (results.html) jedoch als "Neutral" gewertet
SOLL: jumpToQuestion erzeugt 99 und wird als "Übersprungen" gewertet

IST: "Doppelt gewichten" + jumpToQuestion -> NaN
SOLL: 99

Verwandtes Ticket, da es jumpToQuestion betrifft: #16

**Comment by lrusch** [comment]
Hallo Mathias,
hast Du Lust mir Zugriff auf das Repo zu geben? Ich habe da zwei kleine Anpassungen für 1 und 3, für die ich einen PR stellen möchte. Als Diskussionsgrundlage sozusagen. Felix hatte dich vielleicht schon vorgewarnt. Die Wertung als Neutral schaue ich mir dann noch an.

Viele Grüße
Lars

**Comment by msteudtn** [comment]
Hallo @lrusch (Lars),

Einladung ist erfolgt. Besten Dank fürs Einarbeiten und die Mithilfe. :)

Mathias
