### ISSUE TITLE
Credentials zur Datenbank in definition.js eingeben

### ISSUE THREAD

**Issue by fenglisch** [msteudtn/Mat-O-Wahl#19]
Mit dem Ziel, die definition.js zur zentralen Config-Datei zu machen, sollten hier auch die Credentials der Datenbank eingegeben werden, in die die Nutzer*innendaten geschrieben werden (aktuell werden diese in die vote_db.php eingegeben):
- $servername
- $username
- $password
- $dbname

Weitere Angaben, die hier getroffen werden könnten:
- Name der Tabelle
   - Standard ist "Results", aber falls abweichend, kann das hier geändert werden
   - Für den Fall, dass eine Datenbank mehrere solcher Tabellen aus verschiedenen Mat-O-Wahl-Instanzen enthält)
- Ob IP-Adresse gespeichert werden soll oder nicht
   - z. B. über eine Zeile, die man einfach auskommentieren muss
   - In vote_db.php muss man das aktuell manuell eingeben (Zeile 41: `VALUES ('0.0.0.0', '$timestamp', ...` )
   - In vote_txt.php kann das bereits über auskommentieren gemacht werden (Zeile 86)

**Comment by msteudtn** [comment]
Die Datenbank-Abfrage erfolgt per PHP im Backend. 
Wenn man die Zugangsdaten in der `DEFINITION.JS` eintragen würde, hätte jeder Webseiten-Besucher Zugriff auf die Informationen (im Frontened) und könnte dann Schindluder treiben. :( 

Mir ist außerdem keine Möglichkeit bekannt, 
* die Informationen sicher (verschlüsselt) abzulegen
* per JavaScript eine MySQL / MariaDB-Abfrage auszuführen (Ich meine kein REST oder SOAP oder AJAX. Diese setzten am Ende auch wieder auf Backend-Techniken.)
