### ISSUE TITLE
Statistische Auswertung: Einstellung über Opt-In vs. Opt-Out in definition.js anstatt in output.js

### ISSUE THREAD

**Issue by fenglisch** [msteudtn/Mat-O-Wahl#20]
Die definition.js enthält an entsprechender Stelle (ganz unten) einen Hinweis darauf, dass die Änderung von Opt-Out zu Opt-In durch das Auskommentieren der Zeile ~60 in der output.js erfolgen kann. Da man dadurch jedoch eine weitere Datei anpassen muss, wäre es einfacher, wenn diese Einstellung direkt in der definition.js getroffen werden könnte.

Zusätzliche Bemerkung:
Meiner Meinung nach ist in der definition.js und der output.js jeweils in den Kommentaren eine Verwechslung von Opt-Out und Opt-In aufgetreten. Es müsste heißen:
- `Das entspräche dem Opt-In-Verfahren.` (definition.js)
- `Zeile auskommentieren/aktivieren und Opt-Out erzwingen` (output.js)

**Comment by fenglisch** [comment]
Da Opt-Out sowieso keine Möglichkeit zu sein scheint, ist wohl auch dieses Ticket hinfällig

**Comment by msteudtn** [comment]
ich stimme zu.
Mit #35 wird es, meiner Meinung nach, auch eine brauchbare Alternative geben. :)
