### ISSUE TITLE
fnToggleSelfPosition in #resultsByPartyTable zeigt nicht die Änderung der eigenen Position an

### ISSUE THREAD

**Issue by fenglisch** [msteudtn/Mat-O-Wahl#27]
Wenn ich in der #resultsByPartyTable über die Buttons meine eigene Position ändere, führt das zu einer Anpassung des Rankings, aber der Button zeigt mir nicht an, dass ich meine Antwort geändert habe.

Außerdem wäre eine ID analog zu #selfPosition0 in der #resultsByThesisTable praktisch, um die Buttons mit CSS zu stylen, aber ist kein Muss (es funktioniert ja auch der Attribut-Selektor `[onclick^="fnToggleSelfPosition]"` ).

**Comment by msteudtn** [comment]
Sollte mit #30 erledigt sein.

**Comment by fenglisch** [comment]
Funktioniert!
