### ISSUE TITLE
nur die letzte Erweiterung lädt aus der Liste der Add-Ons

### ISSUE THREAD

**Issue by msteudtn** [msteudtn/Mat-O-Wahl#32]
Wenn mehrere Erweiterungen geladen werden, wird nur die letzte Erweiterung geladen.

Der Bug entsteht durch die `window.onload`-Funktion. Alle Erweiterungen hängen sich an das `onload`-Ereignis aber nur die letzte Erweiterung darf am Ende darauf zugreifen.

Als Alternative bietet sich die `window.addEventListener("load", function)` an.
https://developer.mozilla.org/de/docs/Web/API/Window/load_event 

Aufgefallen ist es in #21.

**Comment by msteudtn** [comment]
Sollte mit https://github.com/msteudtn/Mat-O-Wahl/pull/34 erledigt sein.

**Comment by fenglisch** [comment]
Kann bestätigen, dass es funktioniert!
