### ISSUE TITLE
Abfrage nach statistischer Auswertung als letzter Schritt vor dem Ranking

### ISSUE THREAD

**Issue by fenglisch** [msteudtn/Mat-O-Wahl#35]
## Hintergrund
Durch die Aus der Opt-Out-Variante stellt sich mir die Frage, wie dennoch Nutzer:innen dazu bewogen werden können, der Datenübertragung aktiv zuzustimmen. Den Schalter halte ich für die Opt-Out-Variante als perfekt geeignet, aber ich würde selbst nicht auf die Idee kommen, hierüber aktiv zuzustimmen. Das zeigen auch unsere Daten, dass wir seit dem Umstieg auf deutlicher weniger Ergebnisse haben.

## Vorschlag
Anstelle des Schalters könnte nach der letzten These und vor dem Ranking eine Abfrage erscheinen. Die Website https://www.hownormalami.eu/ hat das meiner Meinung nach gut umgesetzt:
![grafik](https://user-images.githubusercontent.com/61431524/123440899-9506d200-d5d3-11eb-98b2-75a5145085d6.png)

Auf den Mat-O-Wahl übertragen könnte das so aussehen:
![grafik](https://user-images.githubusercontent.com/61431524/123441030-b23ba080-d5d3-11eb-8c53-1da810730aba.png)

**Comment by msteudtn** [comment]
So, ist jetzt in #38 drin. :)

Auf dem Smartphone nimmt die Abfrage teilweise den kompletten Bildschirm ein.

Auf dem Desktop sieht man schon das Ergebnis im Hintergrund. Das finde ich aber nicht tragisch. So ähnlich kennt man es vielleicht auch von den "Bitte deaktivieren Sie Ihren Adblocker"-Abfragen. ( ... habe ich gehört ;) )

**Comment by fenglisch** [comment]
Klasse! Gefällt mir richtig gut.

Ist nicht dringend, aber vielleicht je nach Gestaltung ganz sinnvoll: Wäre es möglich, den Overlay dunkler zu machen, sodass man am Desktop weniger durchscheinen sieht? In CSS habe ich dafür nichts gefunden.

**Comment by msteudtn** [comment]
man kann den folgenden CSS-Code für die **Transparenz** zu seinen Stylesheets hinzufügen

```css
.modal-backdrop {
	opacity: 0.9 !important;
}
```

Das ist die Bootstrap-Klasse für das `Modal` (das "Popup"-Fenster). Mit dem `!important`-Hinweis wird sie auch nicht überschrieben.

**Comment by msteudtn** [comment]
man kann den folgenden CSS-Code für die **Transparenz** zu seinen Stylesheets hinzufügen

```css
.modal-backdrop {
	opacity: 0.9 !important;
}
```

Das ist die Bootstrap-Klasse für das `Modal` (das "Popup"-Fenster). Mit dem `!important`-Hinweis wird sie auch nicht überschrieben.

**Comment by fenglisch** [comment]
Super, funktioniert ausgezeichnet!
