### ISSUE TITLE
Wieder ein Textfeld zwischen #resultsHeading und #resultsShort einfügen

### ISSUE THREAD

**Issue by fenglisch** [msteudtn/Mat-O-Wahl#37]

**Comment by msteudtn** [comment]
Das lässt sich vermutlich mit einem kleinen "Hack" einfacher lösen als mit einer neuen Variable. :)

In der `i18n/i18n_de.js` die folgende Variable anpassen. (ein abschließendes `</h1>` und wieder ein öffnendes `<h1>` einfügen.)

`var TEXT_RESULTS_HEADING = "Übereinstimmung mit den Positionen</h1> <p>mein Text unter der Überschrift</p> <h1>"`

Das Ergebnis sieht dann z.B. so aus:
```html
<div id="resultsHeading">
  <h1>Übereinstimmung mit den Positionen</h1> 
    <p>mein Text unter der Überschrift</p> 
  <h1></h1>
</div>
```
Einziger Nachteil wäre, dass man eine "leere" Überschrift hat. Ich gehe aber davon aus, dass auch Screenreader diesen "Fehler" verzeihen können.

**Comment by fenglisch** [comment]
Auch smart. Mein Hack war, das einfach in die index.html hard zu coden, funktioniert auch:
```html
<div id="resultsHeading">
	&Uuml;berschrift f&uuml;r die Ergebnisse/Resultate (ungenutzt) <br /> Headline for the results (unused) 
</div>

<div id="resultsIntro">
	Das Ranking basiert auf der Übereinstimmung deiner Antworten mit den Angaben der Initiativen. Klicke auf eine Zeile, um mehr über die Initiative zu erfahren. <a href="#resultsButtonTheses">In der Tabelle darunter &darr;</a> kannst du die Antworten der Initiativen miteinander vergleichen.<br> 
</div>

<div id="resultsShort">
	Ergebnisse / Resultate der Parteien in tabellarischer Form <br /> Table with results (short) - DOM / id = "resultsShortTable"
</div>

```
