### ISSUE TITLE
DB-Tabellenname in db_settings.php definieren

### ISSUE THREAD

**Issue by fenglisch** [msteudtn/Mat-O-Wahl#43]
Wenn die Datenbanktabelle anders als `Results` heißen soll, muss ich diese Änderung an mehreren Stellen eintragen, was fehleranfällig ist:
- In der `results_db.sql` dreimal (lässt sich vermutlich nicht ändern, außer ich importiere die Tabelle als `Results` und benenne sie dann um)
- In der `vote_db.php` einmal (relativ versteckt)
- In der `read_db_write_text.php` einmal (ebenfalls versteckt)

Wäre es möglich, den Tabellennamen als Variable in der `db_settings.php` zu definieren, sodass andere Dateien darauf zugreifen?

**Comment by msteudtn** [comment]
Jain.

Für den SQL-Import kann die Datenbank nur Text verarbeiten und keine Variablen. 

Sobald der Tabellenname aber einmal feststeht (und dann in der `db_settings.php` drin steht), sollte man ihn aber auch als Variable definieren können.

**Comment by fenglisch** [comment]
Super! Das mit der SQL-Datei habe ich mir schon gedacht. Hier ist die nachträgliche Umbenennung (direkt im Anschluss an den Import) aber auch eine gute Methode. Wenn der Tabellenname in die anderen beiden Dateien übernommen werden könnte und die entsprechend gar nicht mehr angepasst werden müssten, wäre das schon super.

**Comment by msteudtn** [comment]
Die Möglichkeit den Tabellennamen anzugeben ist nun in den `/extras/statistics/db_settings.php` drin.

Die Standard-Tabelle heißt `Results` kann aber auch umbenannt werden. Wenn die Tabelle umbenannt wird (Zeilen 16, 27 und 33 in der `results_db.sql`), muss die `db_settings.php` entsprechend angepasst werden.

**Comment by fenglisch** [comment]
Funktioniert ausgezeichnet, vielen Dank!
Der komplette Prozess (SQL importieren und umbenennen, `db_settings.php` anpassen, `definition.js` anpassen, ein Dummy-Ergebnis erzeugen, Datenbank checken, `read_db_write_text.php` aufrufen, `results.js` anpassen und `results.html` aufrufen) waren jetzt nur wenige Minuten und (mit etwas Übung) auch nicht fehleranfällig.
