### ISSUE TITLE
Web-Interface zum Bearbeiten der parteien.csv

### ISSUE THREAD

**Issue by fenglisch** [msteudtn/Mat-O-Wahl#60]
# 1. Hintergrund

Mehrere unserer Partner:innen (v. a. Kommunen und Freiwilligenagenturen) äußern den Wunsch, dass sie die Initiativen-Daten im Mitwirk-O-Mat (also die `parteien.csv`) gerne selbst bearbeiten würden, um mehr Handhabe zu bekommen und weniger von uns abhängig zu sein. Aktuell müssen sie die Änderungswünsche immer uns schicken und wir aktualisieren die Datei dann manuell direkt auf dem Server - wenn unsere Partner:innen das selbst machen könnten, hätten wir also auch weniger Arbeit. Ihnen Zugriff auf den entsprechenden Ordner auf dem Server zu geben, ist keine Option, weil das die technischen Fähigkeiten unserer Partner:innen bei Weitem übersteigt und zu fehleranfällig wäre. Die Idee ist daher, ein Web-Interface zu programmieren.

# 2. User Story

**SZENARIO**: Gemeinsam mit der Musterstädter Freiwilligenagentur erstellen wir einen Mitwirk-O-Mat. Dafür haben wir eine Limesurvey-Umfrage erstellt, die von 35 Musterstädter Initiativen ausgefüllt wurden. Ihre Daten haben wir automatisch in den Mitwirk-O-Mat übertragen. In den Wochen nach der Veröffentlichung wird die Online-Umfrage von 13 weiteren Initiativen ausgefüllt, die nun doch im Musterstädter Mitwirk-O-Mat dabei sein möchten. Außerdem schreiben fünf Initiativen der Freiwilligenagentur, dass ihre Daten nicht ganz passen und geändert werden sollen.

**IST**: Die Freiwilligenagentur leitet die Änderungswünsche an uns, das Team vom Mitwirk-O-Mat, weiter, damit wir sie umsetzen können. Außerdem exportieren wir die Limesurvey-Antworten der neuen Initiativen und tragen sie in den Mitwirk-O-Mat ein.

**SOLL**: 
1. Die Freiwilligenagentur hat einen passwortgeschützten Zugang zu einem Online-Formular.
2. Hier sehen sie, dass 13 weitere Initiativen die Online-Umfrage ausgefüllt haben. Sie können sich anschauen, was sie geantwortet haben (z. B. ob alle wichtigen Felder ausgefüllt wurden), und die Initiativen-Daten dann per Klick in den Mitwirk-O-Mat übertragen. 3. Ebenfalls können die Mitarbeiter:innen der Freiwilligenagentur die Daten der bereits eingetragenen Initiativen anpassen und dadurch deren Änderungswünsche selbstständig umsetzen.

# 3. Anforderungen
1. Optional: Schnittstelle zu LimeSurvey (um die Daten von dort zu exportieren)
2. Optional: Eingebautes Skript (z. B. in Python), mit dem die Limesurvey-Daten in das passende Format für den Mitwirk-O-Mat umgewandelt werden
   - Ein Skript zum manuellen Ausführen ist schon vorhanden, kann ggf. weiterentwickelt werden)
3. Schnittstelle zur `parteien.csv`, um die neuen LimeSurvey-Daten dort einzutragen und um bereits eingetragene Daten manuell im Browser anpassen zu können.
4. Schlichtes Web-Interface
5. Passwortgeschützter Zugang zu verschiedenen Bereichen
    - Ein Mitwirk-O-Mat enspricht einem Bereich; die Musterstädter Freiwilligenagentur kann mit ihrem Zugang also nur auf den Musterstädter Mitwirk-O-Mat zugreifen und nicht auf die Daten des Beispielheimer Mitwirk-O-Maten
    - Wir vom Team des Mitwirk-O-Maten können mit unserem (Super)Admin-Zugang auf alle Bereiche zugreifen.
6. Das alles in Open Source

# Finanzierung
Im Rahmen eines Förderprojektes könnte die Entwicklung dieses Web-Interfaces in 2022 (teil-)finanziert werden - je nach Umfang.

**Comment by fenglisch** [comment]
Hey @msteudtn ! :-)

Ich wollte in diesem Ticket erstmal den aktuellen Stand festhalten, damit du eine Ahnung hast, was sich unsere Partner:innen gerade von uns wünschen. Für eine Ausschreibung könnte das tatsächlich in Kürze schon relevant sein - also nicht, dass das Web-Interface bis dahin schon fertig sein müsste, aber dass wir wissen, wie viel Aufwand das wäre und ob wir das (zu welchem Preis) versprechen könnten.

Mir ist klar, dass das mit dem Kern des Mat-O-Wahl nicht mehr viel zu tun hat, aber du kennst dich ja auch sonst mit Programmierung aus: Kannst du eine grobe Schätzung abgeben, wie viel Aufwand (in Zeit bzw. in Geld) das sein könnte? Das würde uns für die Kommunikation mit unseren Partner:innen sehr helfen!

Danke dir und alles Gute :-)

**Comment by msteudtn** [comment]
So, wie ich das verstehe, haben wir folgenden, prinzipiellen Ablauf, richtig?

- Initiative XY aus Musterstadt
- (online) Limesurvey-Umfrage durch die Initiative
- Die Frewilligenagentur Musterstadt erhält eine Übersicht aller Limesurvey-Antworten aus Musterstadt
- Die Limesurvey-Antworten werden mit einem manuellem Skript in die `PARTEIEN.CSV`-Datei exportiert

Jetzt möchte die Initiative XY ihre Angaben ändern.

- Kann die Initiative wieder auf ihre eigenen Umfrage und ihre alten Limesurvey-Antworten zurückgreifen?
- ... oder müssen sie alles neu eintragen? (bzw. ist der Punkt "_3. Anforderungen -> 3. Schnittstelle_" dafür gedacht?)
- ... und wird die Freiwilligenagentur bei einer Änderung (oder einem neuen Eintrag) informiert?

**Comment by fenglisch** [comment]
Also der Ablauf ist aktuell folgendermaßen:

# IST

1. Die Freiwilligenagentur (FWA) legt ein Thesenset fest.
2. Wir tragen die Thesen in eine Limesurvey-Umfrage ein.
3. Die FWA leitet den Link zur Online-Umfrage an alle Initiativen weiter, damit diese ihre Antworten auf die Thesen dort eintragen können.
4. Die Initiativen-Antworten trudeln bei uns ein.
5. Nach x Wochen exportieren wir die Antworten aus LimeSurvey, formatieren sie manuell mit unserem Python-Skript um und erhalten dadurch die `parteien.csv` für den Mitwirk-O-Mat.
6. Der fertige Mitwirk-O-Mat wird veröffentlicht.

_Ab hier gibt es zwei verschiedene Dinge, die unabhängig voneinander und parallel passieren können. Um zu zeigen, dass der Ablauf nicht streng chronologisch ist, gibt es jetzt die Stränge A und B_

A7. Beim Ausfüllen fällt einer Initiative ein, dass ihre Antwort bei einer der Thesen anders sein sollte oder dass die Kurzbeschreibung besser sein könnte oder dass ihr Website-Link am Ende nicht stimmt (oder oder oder)
A8. Deshalb schreiben sie der FWA eine Mail und bitten darum, die entsprechende Änderung vorzunehmen. Dafür müssen sie nicht nochmal alle Daten eintragen, sondern schreiben nur in die Mail: "Bei These 5 bitte die Antwort von 'Neutral' auf 'Zustimmung' ändern" (oder "bitte ändert unseren Link zu folgendem: https://...). Nur wenn die Antworten vorne und hinten nicht passen, ist es sinnvoll, wenn sie die Limesurvey-Umfrage nochmal komplett von vorne ausfüllen.
A9. Die FWA hat selbst keinen Zugriff auf die `parteien.csv` und leitet die Mail daher einfach an uns weiter. Wir nehmen die Änderung vor und melden zurück, dass das erledigt wurde. Ggf. meldet die FWA jetzt noch an die Initiative, dass die Änderung wie gewünscht vorgenommen wurde.

B7. Nach der Veröffentlichung des Mitwirk-O-Maten werden weitere Initiativen darauf aufmerksam und wollen auch dabei sein. Sie füllen die Limesurvey-Umfrage aus, die immer noch online ist.
B8. Bei uns trudeln weiterhin Initiativen-Antworten ein. Einmal pro Monat übertragen wir diese in den Mitwirk-O-Mat (erneut manuell mit dem Python-Skript, siehe 5.)
B9. Wir melden der FWA, dass wir y weitere Initiativen in den Mitwirk-O-Mat eingetragen haben.
Anm.: Dadurch, dass wir die Aktualisierung nur einmal pro Monat vornehmen, kommt es vor, dass Initiativen die Online-Umfrage ausfüllen und dann erwarten, dass sie sofort danach im Mitwirk-O-Mat zu finden sind. Wenn sie merken, dass das nciht der Fall ist, schreiben sie der FWA eine Mail. Diese kann auch nichts machen und leitet die Mail daher uns weiter. Wir nehmen dann die Aktualisierung vor (ggf. früher als geplant) und melden zurück, dass die Initiative jetzt im Mitwirk-O-Mat zu finden ist.

Das Problem ist, dass die FWA keinen Zugriff auf die Daten im Mitwirk-O-Mat hat und deswegen immer von uns abhängig ist. Abgesehen davon, dass das nicht besonders effektiv ist, entsteht dadurch auch kein Gefühl der Verantwortung für das Tool (kein digitales Empowerment, wie die FWA es aber erfahren sollen

# SOLL

Deswegen soll es ein Web-Interface geben, wodurch die Szenarien A und B folgendermaßen verändert werden (die Schritte 1 bis 6 bleiben unverändert):

A7. Bleibt gleich
A8. Die FWA erhält die Mail mit dem Änderungswunsch. Sie loggt sich jetzt in der Web-Interface ein und sucht dort den Datensatz zu der entsprechenden Initiative. Hier ändert sie die Antwort der Initiative auf Frage 5 und den Website-Link (oder was auch immer). Die FWA-Mitarbeiterin speichert die Änderungen und diese werden sofort (oder innerhalb kurzer Zeit) auf den Mitwirk-O-Mat übertragen (also in die `parteien.csv)`.
A9. Im Live Mitwirk-O-Mat prüft die FWA-Mitarbeiterin, ob jetzt alles richtig ist, und meldet zurück, dass die Änderung wie gewünscht vorgenommen wurde.

B7. Bleibt gleich.
B8. Im Web-Interface sieht die FWA-Mitarbeiterin, dass die Limesurvey-Umfrage von y weiterein Initiativen ausgefüllt wurde. Sie kann sich die Antworten anschauen und ggf. ändern (z. B. um Rechtschreibfehler zu korrigieren). Dann kann sie auswählen, dass die Änderungen in den Mitwirk-O-Mat übertragen werden sollen. Dadurch aktualisiert sich die `parteien.csv`.


Anmerkung: Es würde erstmal ausreichen, wenn sich das Szenario A mit dem Web-Interface umsetzen ließe (dafür bräuchte es also nur eine Schittstelle zum Mitwirk-O-Maten und nicht zu LimeSurvey).

**Comment by msteudtn** [comment]
Hallo,

ist dieses Ticket noch relevant, da inzwischen eine alternative Schnittstelle in der Entwicklung ist?

**Comment by fenglisch** [comment]
Eigentlich nicht. Das hier wäre eine andere Schnittstelle, aber wir haben das Konzept damals nur als Ersatz entwickelt, wenn die andere Schnittstelle nicht zusammengekommen wäre. Ich bin von diesem Konzept auch nicht wirklich überzeugt und es kam dazu auch keine Anfrage mehr, weil wir das jetzt anders lösen. Also gerne schließen.
