### ISSUE TITLE
Schnittstelle zur Freinet-Datenbank für den Mitwirk-O-Mat

### ISSUE THREAD

**Issue by fenglisch** [msteudtn/Mat-O-Wahl#63]
### Bisherige Idee
Die Idee ist nicht neu, weil sich die meisten Freiwilligenagenturen (FWA), die Freinet schon nutzen (was auf die meisten FWA zutrifft), eine Schnittstelle zwischen den beiden Systemen wünschen. Unsere bisherigen Ideen gingen in die Richtung, die Erfassung der Initiativen-Daten über das Freinet-Formular durchzuführen und die Daten dann so umzuformatieren, dass sie für den Mitwirk-O-Mat (MOM) lesbar sind. Aus mehreren Gründen haben wir diese Idee wieder verworfen, u. a. weil sie nur Extra-Schritte einbauen und keinen echten Mehrwert bringen würde.

### Wie Freinet funktioniert
Relevant für uns ist an dieser Stelle Folgendes (hier am Beispiel von [Münster](https://www.freiwilligenagentur-muenster.de/de/engagieren/mehr-aktuelle-angebote/), ist aber fast immer gleich): Ich stelle die Filter entsprechend meiner Interessen ein und führe dann die Suche aus. Mir werden alle Angebote, die auf die Kriterien zutreffen, als ungeordnete Liste angezeigt. Wenn ich auf ein Angebot klicke, werden mir mehr Infos angezeigt. Teilweise werden mir die Einrichtung, die das Angebot eingestellt hat, und die Kontaktdaten angezeigt (wie in Münster). Häufig (wie hier in [Lüneburg](https://www.buergerengagement-lueneburg.de/htmls/zeitspenden.html)) werden mir als Nutzer die Einrichtung und die Kontaktdaten nicht angezeigt, damit ich erstmal Kontakt mit der FWA aufnehmen muss, die mich dann berät und ggf. für mich den Kontakt mit der Einrichtung aufnimmt. Egal ob mir die Einrichtung angezeigt wird oder nicht: Ich kann mir als Nutzer keine Liste aller Angebote von einer Einrichtung anzeigen lassen, sondern nur die Liste aller Angebote, die auf ein oder mehrere Kriterien zutreffen (und die Einrichtung ist kein Kriterium). Als FWA kann ich mir im Backend aber solch eine Liste aller Angebote einer Einrichtung anzeigen lassen, die Daten sind also vorhanden.

**Einbindung von Freinet:** In den meisten Fällen wird Freinet als iframe eingebunden (so auch in Münster und Lüneburg). Die Datenbank bietet aber auch drei API's (https://www.freinet-online.de/api/). Der [ASB Hamburg](https://www.asb-hamburg.de/freiwillig-aktiv/zeitspender/freiwilligen-jobs/) bindet Freinet hierüber ein.

### Konkrete anstatt allgemeine Ergebnisse
Jetzt haben wir eine neue Idee: Der Grund, weshalb sich die FWA eine Schnittstelle zwischen Freinet und MOM wünschen, ist der, dass die Ergebnisse, die im MOM angezeigt werden, relativ allgemein und unkonkret sind. Es werden keine konkreten Tätigkeiten oder "Stellen" vorgeschlagen (z. B. Buchhaltung oder Fahrdienst), sondern die Einrichtungen/Organisationen/Vereine darüber. Für kleine Initiativen ist diese Sichtbarkeit wertvoll, aber größere, bereits bekannte Einrichtungen haben wenig davon; wenn ich als Nutzer z. B. die AWO vorgeschlagen bekomme und diese dann kontaktiere, dann muss die AWO selbst rausfinden, in welchen ihrer vielen Bereiche ich passe. Besser für die AWO wäre es, wenn ich als Nutzer direkt in einen konkreten Bereich bzw. für eine konkrete Tätigkeit vermittelt würde. Bisher ließe sich das dadurch umsetzen, dass die AWO unsere Online-Umfrage viele Male für jede Tätigkeit ausfüllt. Das hätte aber mehrere Nachteile:
1. Die Antworten auf die Fragen würden sich für die verschiedenen Tätigkeiten nicht großartig unterscheiden, wäre also unnötige Arbeit.
2. Das Ranking wäre überfüllt (um nicht zu sagen vollgemüllt) mit Ergebnissen von der AWO (und anderen großen Einrichtungen)
3. Der Aufwand zur Aktualisierung ist hoch: Wenn ein Bereich im MOM geführt ist, für den zwei Freiwillige gesucht werden, und die gefunden sind, sollte der Bereich wieder entfernt werden. Gleichzeitig müssten ständig neue Bereiche eingetragen und aktualisiert werden. Das wäre aber aufwendig, da die Einrichtungen ihre Daten nicht selbst aktualisieren und einpflegen können, sondern wir als MOM-Team das machen müssen.

Aus diesen Gründen ergibt es keinen Sinn, die Daten für die konkreten Bereiche und Tätigkeiten direkt in den MOM einzutragen. Die Daten hierfür sind aber in vielen Fällen schon da, und zwar in der Freinet-Datenbank. Die Frage ist also, wie diese Daten auf passende Art und Weise implementiert und angezeigt werden können.

### Aus Nutzer:innen-Sicht
Ich fülle den MOM wie gewohnt aus und lasse mir am Ende das Ranking anzeigen. Bei meinem Top-Vorschlag klicke ich auf "Weitere Infos ausklappen". Hier erscheint jetzt wie gewohnt eine kurze Beschreibung und neuerdings darunter eine Liste mit den Bereichen und Tätigkeiten, für die diese Einrichtung Freiwillige sucht.
- Szenario A: Die Angebote sind durch ihren Namen kurz beschrieben. Es sind Links und wenn ich draufklicke, öffnet sich die ausführliche Info-Seite (von Freinet) in einem neuen Fenster
- Szenario B: Zu jedem der aufgelisteten Angebote einer Einrichtung habe ich wiederum die Möglichkeit, weitere Infos anzeigen zu lassen. Diese klappen dann innerhalb des MOM (also innerhalb der Ranking-Tabelle) als eine Art Steckbrief aus

### Aus technischer Sicht
Wenn es für die Einrichtung, die im MOM angezeigt wird, bereits Daten in Freinet gibt, dann werden diese Datensätze verknüpft. Hierfür muss vermutlich manuell gesagt werden: Dieser Eintrag im MOM gehört zu dieser Einrichtung in Freinet

Szenario 1: Über eine API werden die konkreten Angebote einer Einrichtung innerhalb der Ranking-Tabelle angezeigt.
Szenario 2: Die Liste der Angebote einer Einrichtung wird innerhalb der Ranking-Tabelle als iframe (im iframe) angezeigt.

## Fragen
Freinet-seitig: Zwar bietet Freinet bereits API's aber vermutlich erlaubt keine dieser die Abfrage, die wir hier bräuchten. Mangels technischen Verständnisses wissen wir aber noch nicht genau, was die Produkt-API bereits kann und würden das als Nächstes direkt von den Freinet-Devs erfragen.

MOM-seitig: Die Frage ist natürlich auch, wie der Mat-O-Wahl diese Daten abrufen und anzeigen kann und wie viel Aufwand es wäre, ihn hierfür aufzurüsten. Hast du da eine grobe Vorstellung, wie aufwendig das werden könnte?

Finanzierung: Wäre nicht das Problem.

**Comment by fenglisch** [comment]
<img width="704" alt="Capture" src="https://user-images.githubusercontent.com/61431524/159737897-4b5ebdeb-b5ed-4f2b-b627-6bd23dc6a4ea.PNG">

Als Visualisierung, wie ich mir die Liste vorstelle (am Beispiel des Lüneburger Mitwirk-O-Maten). Die Links führen dann jeweils auf die konkreten Angebotsseiten von Freinet, z. B.https://www.freinet-online.de/query/iframe/detail.php?agid=52&styleid=4&frametyp=2&do=go&submit=Suchen&hideund=1&detail=123865

**Comment by msteudtn** [comment]
Hallo,

kennt ihr die **ID-Nummern der jeweiligen Angebote**? Falls ja, könnte man vermutlich den **Verein und seine Angebote direkt auslesen**. Also so etwas in der Art:

`www.freinet-online.de/query/api.php?id=12345`

Dann würde in der `VEREINE.CSV` die ID-Nummern hinzugefügt und wir bräuchten ein neues Add-On, welches sie wieder interpretiert. z.B.

```
Verein_lang: ; "Arbeiter-Samariter-Bund"
Verein_Beschreibung: ; "Wir helfen hier und jetzt [...] etwas dabei. FREINET-ID-12345"
```

### Aufwand

Das **Szenario A** ist in jedem Fall einfacher zu bewerkstelligen, da es am Ende _nur_ ein Link zu Freinet ist.

Das **Szenario B** wäre eine API-Abfrage. Hier stellen sich weitere Fragen, wie
* Muss der Inhalt schon geladen sein, wenn die Nutzer die Infobox öffnen? (also fragen wir 100 Vereine gleichzeitig ab?)
* Oder wird der Inhalt zeitverzögert geladen?
* Welche Informationen bekommen wir zurück? (Angebote, Adresse, Ansprechpartner, ...)
* Bekomme ich eine JSON- oder XML-Antwort zurück?
* Gibt es überhaupt eine API-Abfrage, bei der ich den Verein direkt abfragen kann?
* usw.

Ob das möglich ist, wissen sicherlich die Jungs und Mädels von Freinet am besten. :) Am besten wir setzen uns alle mal gemeinsam zusammen.

**Comment by fenglisch** [comment]
Zu den Freinet-ID-Nummern: Wir bräuchten ja nicht die ID-Nummern der sich ständig ändernden Angebote (sonst müssten wir die `VEREINE.CSV` auch ständig ändern), sondern die ID-Nummern der Einrichtungen, die den Initiativen/Vereinen bei uns im MOM entsprechen. Die würden dann, genau wie du vorschlägst, in die `VEREINE.CSV` eingetragen werden (ob in die Beschreibungszeile oder eine neue Zeile, ist dann ja vermutlich eine Detail-Frage).

Das Szenario B können wir eigentlich gleich verwerfen, das fände ich auch aus Nutzer:innensicht nicht wünschenswert, weil der MOM dann zu voll wird

Szenario A basiert nach meiner Vorstellung aber auch auf einer API-Abfrage. Im MOM soll das dann so funktionieren, dass in der `VEREINE.CSV` wie gesagt die Freinet-ID der Einrichtung eingetragen ist. In der `resultsShortTable` soll dann Folgendes generiert werden:

```
ALT: <p style="cursor: pointer;"> ↓ <span id="resultsShortPartyDescriptionDots0" style="display: none;">...</span>
ALT: <span id="resultsShortPartyDescription0">Der Dachverband der Kieler Sportvereine</span> </p>
NEU: <div id="resultsShortPartyFreinet0"><p>Aktuelle Engagement-Angebote:</p>
NEU:    <ul>
NEU:      <li><a href="https://www.freinet-online.de/query/iframe/detail.php?agid=52&styleid=4&frametyp=2&do=go&submit=Suchen&hideund=1&detail=123865" target="_blank">A Beispiel Angebot MA1</a>
NEU:      <li><a href="https://www.freinet-online.de/query/iframe/detail.php?agid=52&styleid=4&frametyp=2&do=go&submit=Suchen&hideund=1&detail=36504" target="_blank">Ein Tolles Rosengarten Spiel </a>
NEU:   </ul>
NEU:</div>
```

Zu deinen Fragen:
1. Lazyload fände ich sehr sinnvoll
2. Wir bekommen den Namen und die URL des Angebotes zurück. Außerdem muss die Zuordnung zu einer Einrichtung natürlich bekannt sein, damit wir das überhaupt anzeigen können.
3. Ob JSON oder XML, weiß ich nicht, da müsste ich die Vor- und Nachteile kennen.
4. Ob es bereits eine API-Abfrage zu den Freinet-Einrichtungen gibt oder ob die programmiert werden müsste, werde ich erfragen.

**Comment by msteudtn** [comment]
Zwischenstand: 
* Gemeinsame Videokonferenz am Montag, 27.06.2022 gehabt.
* Zusammenarbeit vereinbart.
