### ISSUE TITLE
Mailto-Link in der Ergebnisanzeige

### ISSUE THREAD

**Issue by fenglisch** [msteudtn/Mat-O-Wahl#65]
Die Idee habe ich aus dem Klimafinder (https://klimafinder.netlify.app/). Wenn du alle Fragen beantwortest (ganz egal wie), kommst du zum Ranking, klickst dann auf irgendein Angebot und siehst den Button "Connect me". Dahinter steckt ein komplexer mailto-Link. Wenn du draufklickst, öffnet sich dein Standard-Mail-Programm mit einer vorformulierten Mail mit folgendem Inhalt:
- Variable Empfänger:in(nen)
- Variabler Betreff
- Standard-Anschreiben mit einzelnen variablen Inhalten
- Liste, mit welchen Angeboten ich welche Übereinstimmung hatte (also mein Ranking in Textform)

Für einen Wahlhelfer, also den klassischen Wahl-O-Mat Use Case, braucht es so etwas natürlich nicht, aber für den Mitwirk-O-Mat wäre das umso sinnvoller. Die Nutzer:innen sollen ja, nachdem sie das Ranking sehen, nicht direkt abspringen, sondern Kontakt aufnehmen. So eine vorformulierte E-Mail würde die Hürde dafür sicherlich verringern.

Es könnte auch eingestellt werden, an wen die E-Mail gehen soll, und davon abhängig natürlich der Inhalt:
- Direkt an den Verein, um zu fragen, wie/wo/wann man sich beteiligen kann (dann bräuchte es die Ranking-Liste mit den Übereinstimmungen mit den anderen Vereinen nicht in der Mail)
- An die Freiwilligenagentur, um Interesse an einem konkreten Angebot mitzuteilen und einen Beratungstermin hierzu zu vereinbaren. Gleichzeitig wird das Ranking (z. B. die Top 10) mitgeschickt, damit die FWA mehr über die Person weiß und gezielter beraten kann, nicht nur zu dem einen konkreten Angebot
   - Hintergrund: Für viele FWA's ist die klassische Beratung trotz digitaler Tools ein zentraler Baustein und einige FWA's müssen auch nachweisen, dass sie jährlich soundsoviel Beratungsgespräche geführt haben, um ihre Förderung zu bekommen. Der Mitwirk-O-Mat sollte diesen FWA also mehr und nicht weniger Termine bescheren.

Ich könnte mir das als weiteres Add-On vorstellen, mit einer Datei, wo ich die ganzen Strings inkl. Variablen eingebe (Betreff und Anschreiben). Hier wähle ich auch aus, ob die Mail an eine (in der `parteien.csv` zu hinterlegende) E-Mail-Adresse des Vereins oder an die (in der Add-On-Datei zu hinterlegende) E-Mail-Adresse der Freiwilligenagentur gesendet werden soll. Daraus werden dann die mailto-Links für die Buttons generiert, die in der Ergebnistabelle angezeigt werden.

Was ich mir schwer vorstelle, ist die Übertragung des Rankings in den E-Mail-Text. Wenn das nicht gehen sollte, wäre das zwar schade, aber das Feature wäre trotzdem sinnvoll (theoretisch könnte man bitten, dass der Nutzer ein Screenshot vom Ranking macht und in die Mail einfügt).

Ich weiß nicht, ob der Klimafinder Open Source ist, vielleicht würde ein Blick in deren Code auch helfen.

**Comment by msteudtn** [comment]
Hallo,

eine coole Idee.

Technisch wäre vielleicht wirklich ein Add-On die sauberste Lösung. Ansonsten müsste man anfangen die `parteien.csv` resp. `vereine.csv` mit unendlich vielen Spalten aufzubohren. :(

Das Add-On hätte in der einfachsten Ausführung einige Arrays der Art:

```
emailadresse = ["kontakt@verein.de", "fwa@ort.de", ...]
telefonnummer = ["", "0123 - 456789", ...]
betreff =  ["Anfrage XY", "Anfrage ABC", ...]
inhalt = ["Hallo, ...", ...]
```

... oder in der schönen Variante hätte man eine zusätzliche CSV-Textdatei mit den Inhalten:

| emailadresse | telefonnummer | betreff | inhalt |
| -- | -- | -- | -- |
| kontakt@verein.de | . | Anfrage XY | Hallo, ... |
| fwa@ort.de | 0123 - 456789 | Anfrage ABC | ... |

Das **SOLLTE** auch gar nicht so umständlich sein, da `/SYSTEM/GENERAL.JS -> fnReadCsv(csvFile,fnCallback)` von Haus aus eine Nachfolge-Funktion (nach dem Einlesen einer CSV-Datei) erwartet. Diese Folge-Funktion wäre dann das Schreiben der Daten in die Ergebnisse. :)


Das **Thema "Versenden der Ergebnisse"** würde ich erst mal nach hinten verschieben. Das kommt sicherlich auch darauf an, ob eher die Freiwilligenagentur (FWA) oder doch der Verein angesprochen werden möchte.


Übrigens könnte man mit der Telefonnummer auch **Messenger-Dienste** über einen weiteren Button einbinden. Ein Beispiel wäre z.B. Whatsapps "Click to Chat" https://faq.whatsapp.com/452366545421244/?locale=de_DE

**Comment by msteudtn** [comment]
Hallo,

> Skalierbarkeit

ja, ab einer gewissen Anzahl wird das unübersichtlich.

> Die Telefonnummer bräuchten wir dafür nicht

Ich würde die Telefonnummer noch nicht ad acta legen. Es gibt bestimmt viele Leute, die keinen Mailzugang mehr auf ihrem Smartphone eingerichtet haben. Da bleibt nur noch der Anruf oder der Messenger-Dienst.
Außerdem möchte ich das Add-On gern langfristig anlegen, falls andere Anwender doch die Telefonnummer brauchen. :)

> Für die E-Mail-Adressen wäre es aber am besten, wenn die (irgendwie) mit in der `parteien.csv` stehen würden

Dann stehe ich - ähnlich wie bei den Tickets #44 und #53 (`fragen.csv`) - vor der Frage ob man weitere Spalten oder Zeilen hinzufügen muss. :( 

Alternativ würden die Informationen in einem vorhandenen Textfeld (wie der Partei-Beschreibung) versteckt und müssten dann "herausgefischt" werden. z.B. innerhalb eines `<!-- HTML-Kommentars -->` oder etwas ähnlichem.

Beispiel der normalen `parteien.csv`: https://github.com/msteudtn/Mat-O-Wahl/blob/abbdfccbc29c2f7b44b898d162c651c58532dc7c/data/Obsthausen_Parteien.csv 

> Als zweitbeste Option kann ich mir vorstellen, dass die E-Mail-Adressen in einer zweiten CSV eingetragen werden

Das wäre im Moment mein Favorit. Die **Reihenfolge** müsste dann wie in der `parteien.csv` sein. Aber der **Aufbau** wäre so, wie im Kommentar weiter oben. https://github.com/msteudtn/Mat-O-Wahl/issues/65#issuecomment-1189205493 
Also müsste man keinen Abstand lassen, sondern kann die Kontaktdaten "leicht" wiederfinden. 
Es könnte zusätzlich noch eine Spalte "Beschreibung" geben. Wenn sie ausgefüllt ist, weiß man auch, welcher Verein hinter Karl-Theodor.von-und-zu-1971@t-online.de steckt.

> Der Betreff und das Anschreiben sollten aber meiner Meinung nach weder in einem Array noch in einer CSV stehen

Mein erstes Verständnis war, dass je nach Bedarf die Vereine oder die Freiwilligenagenturen (FWA) angeschrieben werden. Aber ein allgemeines Anschreiben reduziert natürlich den Aufwand. :) 

> Die Idee mit Click-to-Chat ...

siehe oben mit der Telefonnummer. :) 
Aber ja, den genauen Umgang mit Messenger-Diensten und der DSGVO in den FWA kenne ich nicht.

**Comment by fenglisch** [comment]
**Telefonnummer:** Du hast recht, vermutlich ist es sinnvoll, das Add-On so zu bauen, dass die Telefonnummern direkt mit hinterlegt werden können. Die kann dann ja auch für einen Anruf-Button genutzt werden, da viele Freiwilligenagenturen und einige Vereine ja Sprechzeiten haben (und wenn man außerhalb der Sprechzeiten anruft, kann man ja auf die AB quatschen). Und vielleicht gibt es ja auch Freiwilligenagenturen, die man über einen Messenger anschreiben kann, dann wäre Click-to-chat natürlich super.

**E-Mail-Adressen in `parteien.csv`**: Das in ein anderes Feld reinzuwurschteln, fände ich nicht gut. Das machen wir jetzt ja schon mit den Filterkriterien. Da ist für uns der Aufwand auch ziemlich groß, den LimeSurvey-Export so umzuformatieren, dass am Ende die Filter-Kriterien mit im Beschreibungs-String enthalten sind, aber dafür haben wir jetzt eine Lösung gefunden. Mit jeder weiteren Information wird das aber unübersichtlicher und komplizierter. 

Am besten wäre es wohl, wenn die `parteien.csv` nicht aus zwei Spalten und n Zeilen bestehen würde (n = Zahl der Parteien * (Anzahl der Fragen + 6)), sondern aus x Spalten (x = 5 + Anzahl der Fragen x 2) und y Zeilen (y = Anzahl der Parteien). Anders ausgedrückt: Für jede Partei hat eine Zeile und die Daten zur Parteien sind dann in mehreren Spalten. Dann könnte man ja nach meiner Vorstellung hinter den "Pflicht-Spalten" (Allgemeine Angaben und Antworten auf die Fragen) noch weitere optionale Spalten einfügen, die nur ausgelesen werden, wenn ein Add-On aktiviert ist, z. B. die Filter-Kriterien oder E-Mail-Adressen.

*E-Mail-Adressen in separater CSV*: Ja genau, ein Abstand wäre nicht sinnvoll. Das über die Beschreibung abzugleichen, wäre bei vielen Vereinen aber auch nicht unbedingt das einfachste. Ich hab jetzt aber die Formel zur Umrechnung der Zeilennummer des Vereins zur Zeilennummer der E-Mail-Adresse:
(Zeilennummer des Vereins - 1) / (Anzahl der Fragen + 6) + 1 = Zeilennummer der E-Mail-Adresse

Damit lässt sich schnell finden, welche E-Mail-Adresse aktualisert bzw. gelöscht werden muss, wenn sich bei einem der Vereine etwas ändert. Es ist dann immer noch fehleranfälliger, als wenn das alles direkt in der `parteien.csv` wäre, aber da müssen wir einfach gut aufpassen. Jetzt, wo ich drüber nachdenke, wäre es vermutlich doch nicht schlecht, sicherheitshalber den Namen des Vereins auch in der E-Mail-Adressen-CSV einzutragen, auch wenn er da gar nicht ausgelesen wird.

**FWA oder Verein anschreiben**: Nach meiner Vorstellung reicht es, wenn das zentral in der Add-On-Datei vorgegeben ist, an wen die E-Mail gehen soll: Immer an den jeweiligen Verein oder immer an die FWA. Wenn die Mails an die FWA gehen, braucht es die E-Mail-Adressen-CSV gar nicht, sondern die E-Mail-Adresse der FWA wird in der Add-On-Datei hinterlegt. So oder so ist das Anschreiben jeweils gleich: Es werden entweder alle Vereine mit demselben Text angeschrieben (ggf. mit Variablen) oder es wird die FWA mit dem immer gleichen Text angeschrieben (Variablen wären hier wichtig). Das sind dann natürlich zwei verschiedene Texte.

**Comment by msteudtn** [comment]
Ich habe ein paar Tests gemacht und bin darüber gestolpert, dass die gesamte **Ergebniszeile mit einer Klickfunktion belegt** ist. Diese öffnet die Beschreibung der jeweiligen Partei / des Vereins. Hintergrund war, dass man auf dem Smartphone mit seinen Wurstfingern :) einfacher die Zeile antippt als den Text.

![Mat-o-Wahl-Kontaktbuttons](https://user-images.githubusercontent.com/7988551/180598749-a997b31f-e88d-42a6-a922-3933553791fb.png)

Das bedeutet, dass (im Moment) beim Klick auf die Buttons "E-Mail" oder "Telefon" jedes mal die Beschreibung geöffnet / geschlossen wird.

Man könnte die **Klickfunktion wieder reduzieren** oder eine **Zwischenzeile einfügen**. Eventuell könnte die Zwischenzeile sich zusammen mit der Beschreibung öffnen. 

Die Betaversion des Add-Ons liegt hier: https://github.com/msteudtn/Mat-O-Wahl/blob/issue-65-addon-contact-buttons/extras/addon_contacts_in_results.js Das Add-On kann noch nicht viel. Es gibt nur eine E-Mailadresse, eine Telefonnummer und keinen E-Mailtext.

**Comment by fenglisch** [comment]
Wie cool!

Ich glaube, es wäre sinnvoller, wenn die Buttons auch erst versteckt wären und mit ausgeklappt werden. Wenn ich über einen Verein nicht mehr erfahren möchte, dann möchte ich ja wegen dieses Vereins auch keine E-Mail versenden oder einen Anruf tätigen.

Das Problem mit dem Ein- und Ausklappen bliebe dann vermutlich trotzdem, also dass die Beschreibung wieder einklappt, wenn ich auf den Button klicke. Aber dafür finden wir dann bestimmt eine Lösung.

Das Add-On ist natürlich noch nicht fertig, aber schon mal eine Anregung zu den Telefon-Buttons: Es wäre cool, wenn in der Add-On-Datei eingestellt werden kann, welcher Button angezeigt werden soll, also z. B.:
```
var eMail = 1;
var telephone = 0;
```

Damit könnte die Telefon-Option ganz aktiviert werden, falls die Freiwilligenagentur das nicht will. Und selbst wenn die Telefon-Option aktiviert ist, könnte man den Telefon-Button dann über einen CSS @media-Query auf Desktops verstecken, weil vermutlich die wenigsten ein Telefon-Programm auf dem PC haben, sondern dann eher eine E-Mail schreiben. Oder die Telefonnummer wird angezeigt und kann mit dem Handy abgetippt werden. Gleichzeitig könnte die ausgeschriebene Telefonnummer mit einem Tel-Link hinterlegt sein, sodass beides ermöglicht wird, abtippen oder draufklicken. Aber da würde ich jetzt nicht zu viel Hirnschmalz und Arbeit reinstecken, weil ich schätze, dass diese Optionen sowohl von den Nutzer:innen (viele sind ja telefonier-scheu) als auch von den Vereinen und Freiwilligenagenturen weniger nachgefragt sein wird als die E-Mail-Option.

**Comment by msteudtn** [comment]
Zitat aus https://github.com/msteudtn/Mat-O-Wahl/pull/71#issuecomment-1201074297 

> Kleine Änderungsvorschläge [...]
> * Dadurch, dass die beiden neuen Zeilen sich jeweils in einem eigenen div.mow-row-striped befinden, wird das Streifenmuster durcheinandergebracht. Besser wäre es, wenn die drei Zeilen (#resultsShortParty, #resultsShortPartyAddonContactsInResults, #nixTest) alle in einem div.mow-row-striped wären.

Für das Ein- und Ausblenden "zähle" ich die CSS-Klasse `row` in den `<DIV>`s (in der ich dann auch `mow-row-striped` unterbringe). Wenn ich eine zusätzliche Zeile einfüge (oder auch wegnehme), kommt am Ende alles wieder durcheinander. :) 

Abgesehen davon, besteht das "**Streifenproblem**" ja auch beim Textfilter `extras/addon_results_textfilter_by_button.js`. Dort werden die Zeilen ebenfalls so eingeblendet, wie sie ursprünglich vorgesehen waren.

Lösungsansätze:

Man könnte den Rahmen in den extra Zeilen auch einfach entfernen, indem man die CSS-Klasse weglässt. Ich persönliche finde aber, dass die Inhalte dann etwas verloren in der Luft hängen.

Alternativ müsste nach jedem Seiten-Rendern nochmal über die Tabelle gegangen werden und geprüft werden, ob die vorherige Zeile hell oder dunkel war. Das wäre aber etwas für ein sehr langes, verregnetes Wochenende. :) 



> * Super wäre es, wenn der Name des Vereins, bei dem ich als Nutzer auf den Button klicke, als Variable in die E-Mail (und ggf. auch schon in den Betreff) eingefügt werden könnte: "Ich habe Interesse an folgendem Verein: [NAME DES VEREINS]"

Im Entwicklungszweig `issue-65-addon-contact-buttons/`gibt es nun eine aktualisierte Addon-Datei.
https://github.com/msteudtn/Mat-O-Wahl/blob/issue-65-addon-contact-buttons/extras/addon_contacts_in_results.js

**Achtung:** Es ist das Addon mit der zusätzlichen "Testzeile ohne Funktion".

**Comment by fenglisch** [comment]
Ich hab deine Antwort nicht wirklich verstanden... Also das mit dem Streifenproblem beim Filtern schon, das ist mir auch aufgefallen, aber finde ich nicht so schlimm. Dafür die Seite neu rendern wäre echt übertrieben.

Ich stelle mir das mit den neuen Zeilen so vor:
![grafik](https://user-images.githubusercontent.com/61431524/182427561-cfd9bcc1-c6f2-448e-9c6e-91dd5f4faf46.png)

Hab das im Browser so zusammengebastelt, das Ein- und Ausklappen hat funktioniert:
```
<div class="row border rounded mow-row-striped" id="resultsShortParty0" role="row">
   <div class="col col-10 col-md-7" role="cell">
      <strong>Kulturstadt e.&nbsp;V.</strong> (⇗ <a href="https://beispiel.de" target="_blank" alt="Link: Kulturstadt e.&nbsp;V." title="Link: Kulturstadt e.&nbsp;V.">KS</a>)
      <p style="cursor: pointer;"> ↓;  <span id="resultsShortPartyDescriptionDots0" style="display: none;">...</span><span id="resultsShortPartyDescription0" style="">&nbsp;Wir bringen Musik, Theater und Tanz nach Neustadt.<br><small>#12345</small></span> </p>
   </div>
   <div class="col col-2 col-md-1" role="cell"><img src="data/logos/ks.png" class="rounded img-fluid" alt="Logo Kulturstadt e.&nbsp;V."></div>
   <div class="col col-12 col-md-4" role="cell">
      <div class="progress">
         <div class="progress-bar bg-success" role="progressbar" id="partyBar0" style="width:100%;" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100">100% (1 / 1)</div>
      </div>
   </div>
   <div id="resultsShortPartyAddonContactsInResults0" style="flex: 1 1 100%;" class="row border rounded">
      <div class="col" style="text-align: center;">  <a href="mailto:..." role="button" class="btn btn-sm btn-success">Kontakt per E-Mail</a> </div>
      <div class="col" style="text-align: center;">  <a href="tel:+49123456789" role="button" class="btn btn-sm btn-success" aria-pressed="true">Kontakt per Telefon</a> </div>
   </div>
   <div id="nixTest0" style="flex: 1 1 100%;" class="row border rounded">
      <div class="col"> Testzeile ohne Funktion j: 0 </div>
   </div>
</div>
```

Also das ist garantiert nicht sauber, aber ginge das so in die Richtung?

**Comment by fenglisch** [comment]
Vielleicht könnte man auch den ganzen oberen Teil in ein eigenes DIV packen und die Klick-Funktion zum Ein- und Ausklappen nur auf dieses DIV legen, damit es beim E-Mail-Button nicht passiert

Also die drei div.col mit der Beschreibung, dem Logo und dem Balken nochmal in ein eigenes div.row und dieses div.row dann zusammen mit dem neuen div#resultsShortPartyAddonContactsInResults in das bestehende div.mow-row-striped

**Comment by msteudtn** [comment]
> https://github.com/msteudtn/Mat-O-Wahl/issues/65#issuecomment-1202971188 Hab das im Browser so zusammengebastelt, das Ein- und Ausklappen hat funktioniert [...]

Wenn ich das richtig interpretiere, liegen alle Informationen (Beschreibungen, Bilder, Prozentbalken, Kontaktdaten, Testzeile) unterhalb der jeweiligen DIV `resultsShortParty0, resultsShortParty1` usw. Das war auch mein erster Gedanke (Siehe https://github.com/msteudtn/Mat-O-Wahl/issues/65#issuecomment-1193093425) aber auf dem entsprechenden DIV liegt bereits eine Klickfunktion. Dadurch konnte man die Buttons nicht erreichen. :(

> Vielleicht könnte man auch den ganzen oberen Teil in ein eigenes DIV packen und die Klick-Funktion zum Ein- und Ausklappen nur auf dieses DIV legen, damit es beim E-Mail-Button nicht passiert 

Das wäre langfristig vielleicht eine Lösung. Im Moment würde es aber noch mehr Komplexität in das Addon bringen (Prüfen, ob es die "Hauptzeile" ist, abzählen wie viele Extrazeilen es gibt, ausblenden der entsprechenden Zeilen) - besonders, da Ticket #69 noch offen ist. :)

Lange Rede, kurzer Sinn: Das Thema "Streifen beim Filtern" würde ich gern auf "später" verschieben.

**Comment by fenglisch** [comment]
Genau, als aktuell sind die drei `div.col` mit der Beschreibung, dem Logo und dem Balken jeweils direkte children der `div#resultsShortPartyX`. Die `div#resultsShortPartyAddonContactsInResults` und die `div#nixTestX` sind aktuell keine children der `div#resultsShortPartyX`, sondern folgen direkt dahinter.

Mein Vorschlag wäre nun, die drei `div.col` in eine zusätzliche `div.row` zu packen, z. B. mit der ID `#resultsShortPartyGeneralX`, unabhängig davon, ob das Addon aktiviert ist oder nicht. Die Klickfunktion zum Ausklappen könnte dann nur auf dieses `#resultsShortPartyGeneralX` gelegt werden und nicht auf die ganze `div#resultsShortPartyX`. Wenn das E-Mail-Addon nicht aktiviert ist, macht das keinen Unterschied und das zusätzliche div wäre nicht notwendig, aber stört auch nicht, aber sobald das Addon aktiviert ist, würde es was nützen.

**Comment by msteudtn** [comment]
Die Änderungen mit dem zusätzlichen "Klammer-DIV" sind im Moment in diesem Zweig eingepflegt.
https://github.com/msteudtn/Mat-O-Wahl/tree/issue-65-addon-contact-buttons

Wichtig sind folgende Dateien / Hier gab es relevante Änderungen:
* https://github.com/msteudtn/Mat-O-Wahl/blob/issue-65-addon-contact-buttons/system/output.js
* https://github.com/msteudtn/Mat-O-Wahl/blob/issue-65-addon-contact-buttons/extras/addon_contacts_in_results.js

Optional:
* https://github.com/msteudtn/Mat-O-Wahl/blob/issue-65-addon-contact-buttons/extras/addon_limit_results.js
* https://github.com/msteudtn/Mat-O-Wahl/blob/issue-65-addon-contact-buttons/extras/addon_results_textfilter_by_button.js

**Comment by fenglisch** [comment]
Nice, das sieht super aus! Auch mit dem Namen des Vereins im E-Mail-Betreff.

Ein Bug ist mir noch aufgefallen, sicherlich ausgelöst durch den Konflikt zwischen Limit-Results- und Filter-Addon. Vermutlich würde er kaum auffallen, weil er nur auftritt, wenn man auf spezielle Weise mit der Ergebnistabelle interagiert. Vielleicht gibt es aber auch eine weniger umständlichere Abfolge als diese:
1. Öffne https://mitwirk-o-mat.de/issue-65 (die Original-Version mit folgenden Addons aktiviert: `"extras/addon_results_textfilter_by_button.js", "extras/addon_check_iframe_resize_client.js", "extras/addon_limit_results.js", "extras/addon_contacts_in_results.js"`)
2. Beantworte alle Fragen mit "Ja", um zum Ergebnis zu kommen.
3. Klicke auf alle Ergebnisse, um die Beschreibung und die Kontakt-Buttons auszuklappen.
4. Klicke auf "Südfrüchte anzeigen"
5. Klicke auf "Mehr Ergebnisse anzeigen"

-> Bei der Apfelpartei wird die vollständige Beschreibung angezeigt, aber nicht die Buttons. Wenn ich auf die Beschreibung klicke, wird diese eingeklappt, aber die Buttons erscheinen (bei den Neutralen ist das auch so, aber da fällt es kaum auf). Je nachdem, wie die Fragen beantwortet und welcher Filter gewählt wird, passiert es auch bei den anderen Parteien.

Da das sicherlich nur sehr selten auftritt und auch dann noch zu benutzen ist, hat die Behebung dieses Bugs meiner Meinung nach nicht die höchste Priorität. Ich wollte dich aber informieren

**Comment by fenglisch** [comment]
https://github.com/msteudtn/Mat-O-Wahl/issues/65#issuecomment-1231793986 wurde in ein eigenes Issue überführt
