### ISSUE TITLE
Platz 1 in der Ergebnistabelle standardmäßig aufklappen

### ISSUE THREAD

**Issue by fenglisch** [msteudtn/Mat-O-Wahl#66]
Einige wichtige Features werden ja in der Ergebnistabelle erst zu sehen sein, wenn man sie ausklappt. Aktuell ist es nur die Beschreibung, aber es sollen ja die Freinet-Angebotsliste und der E-Mail-Button (und ggf. Telefon-Button) hinzukommen. Umso wichtiger ist es, dass durch das UI direkt erkennbar ist, dass ich da was ausklappen kann und dass da wichtige Dinge stehen.

Meine Idee wäre, dass der 1. Platz in der Liste standardmäßig ausgeklappt ist.

Vorteile:
- Ich sehe auch als unaufmerksame:r Nutzer:in direkt, dass ich mir mehr Infos anzeigen lassen kann und was sich dahinter verbirgt. Dadurch werde ich angeregt, mit dem 1. Platz zu interagieren und auch bei den späteren Ergebnissen die Beschreibung auszuklappen.

Nachteile:
- Wenn der Verein nur eine ganz kurze Beschreibung hat, keine Einträge aus Freinet und keine E-Mail oder Telefonnummer hinterlegt hat, dann denke ich, dass es bei allen Vereinen so aussieht, obwohl bei Platz 2 schon viel mehr stehen könnte. Die Gefahr besteht aber auch, wenn ich Platz 1 manuell ausklappe (was wohl die meisten machen werden).
- Wenn da viel steht (längere Beschreibung, mehrere Einträge aus Freinet), ist auf einem Smartphone bereits der ganze Screen damit bedeckt und ich sehe nicht sofort, dass es unter dem 1. Platz noch weitergeht. Daher wäre es vermutlich schlau, wenn sich differenzieren ließe, ob das Feature auf allen Geräten oder nur bei bestimmter Screen-Weite wirken soll.

**Comment by msteudtn** [comment]
Gute Idee ... und auch die Einwände sind berechtigt.

Eine mögliche Lösung besteht vielleicht darin, die Anzahl nicht fest zu codieren, sondern in der `data/definition.js` zu hinterlegen. So kann man als Anbieter selbst entscheiden, ob man nur einen oder x Vereine / Parteien am Anfang detailliert anzeigen möchte.

Bei den Smartphones sehe ich das Problem weniger, da die Leute vermutlich schnell nach unten durchscrollen. Dann wird ein Unterschied erkennbar.

**Comment by fenglisch** [comment]
Ja, eine Variable hierzu in der definition.js wäre super! Ich hab mir das auch nochmal am Smartphone angeschaut, du hast recht. Selbst wenn ich am Anfang nur meinen Platz 1 sehe, weil der eine lange Beschreibung hat, scrolle ich ja schnell nach unten und sehe, dass es weitergeht.

**Comment by msteudtn** [comment]
Sollte über das neue Addon https://github.com/msteudtn/Mat-O-Wahl/blob/master/extras/addon_show_first_results.js gelöst sein. :)

**Comment by fenglisch** [comment]
Top, funkioniert super!
