### ISSUE TITLE
Ausgeklappte Partei-Antworten werden in der resultsByPartyTable angezeigt, auch wenn Partei durch limit-results versteckt ist

### ISSUE THREAD

**Issue by fenglisch** [msteudtn/Mat-O-Wahl#68]
**Steps to reproduce:**

1. `addon_limit_results` muss aktiviert sein
2. Springe bis zur Auswertung.
3. Klappe unten die `resultsByPartyTable` aus.
4. Klappe die Antworten des zweitplatzierten Ergebnisses an.
5. Reduziere die Anzahl der Ergebnisse, die angezeigt werden, bis nur noch das oberste Ergebnis zu sehen ist.

**Expected behaviour:**
Die ausgeklappten Antworten des zweitplatzierten Ergebnisses werden ebenfalls versteckt

**Actual behaviour:**
Die Antworten bleiben ausgeklappt und lassen sich nicht wieder einklappen, da das div mit der Partei und dem Collapse-Button versteckt ist. Man muss erst wieder mehr Ergebnisse anzeigen lassen, bis die Partei wieder erscheint und man die Antworten einklappen kann.

**Comment by msteudtn** [comment]
Das hier https://github.com/msteudtn/Mat-O-Wahl/blob/issue-68-bug-in-addon-limit-results/extras/addon_limit_results.js sollte nun funktionieren. :)

Es ist noch nicht im Master- / Main-Bereich gelandet.

**Comment by fenglisch** [comment]
Jo, funktioniert! :-)
Danke dir!
