### ISSUE TITLE
Kontakt-Addon kommt nicht mit Sonderzeichen (&) zurecht

### ISSUE THREAD

**Issue by fenglisch** [msteudtn/Mat-O-Wahl#75]
Ist kein großes Problem, da wir die Zeichen in den Vereinsnamen auch ersetzen könnten, aber wäre schön, wenn es dafür einen Quick Fix geben könnte.

Steps to reproduce:

1. Öffne einen Mat-O-Wahl, der mind. 1 Partei/Verein mit dem Sonderzeichen `&` im Titel enthält (möglicherweise sind auch andere Sonderzeichen betroffen, habe ich noch nicht getestet).
2. Klicke bei irgendeinem Ergebnis auf den Kontakt-Button
Behaviour: Die Liste der Ergebnisse am Ende der Mail bricht bei dem Verein mit dem Sonderzeichen ab
3. Klicke bei dem Verein mit dem Sonderzeichen auf den Kontakt-Button
Behaviour: Die E-Mail ist leer

**Comment by msteudtn** [comment]
* Das Addon wurde aktualisiert und in den Master-Bereich eingespielt. 
* Details zu den (kleinen) Änderungen finden sich hier: https://github.com/msteudtn/Mat-O-Wahl/pull/76 
* **Hinweis:** Demnächst erscheint neues Addon mit größeren Änderungen
  - Variablen werden umbenannt, z.B. `CONTACT_BUTTON_EMAIL -> CR_CONTACT_BUTTON_EMAIL`)
  - mehr Optionen, z.B. individuelle E-Mailadressen pro Partei / Verein innerhalb der CSV-Datei
